import {
  GameConstants,
  AsteroidConstants,
  WormholeConstants,
  ExplosionConstants,
  CosmicVelocityConstants,
} from '../types/types';

export const GAME_CONSTANTS: GameConstants = {
  SPACESHIP_MOVE_SPEED: 1.0,
  FIELD_WIDTH: 65,
  FIELD_HEIGHT: 40,
  SMOOTHING_FACTOR: 0.15,
  SWIPE_THRESHOLD: 20,
};

export const ASTEROID_CONSTANTS: AsteroidConstants = {
  INITIAL_ASTEROID_SPEED: 0.2,
  ASTEROID_SPEED_INCREMENT_FACTOR: 0.0000025,
  KMH_SCALING_FACTOR: 300,
  INTERNAL_DISTANCE_INCREMENT_PER_FRAME: 0.15,
  DISPLAY_DISTANCE_EXPONENT: 1.65,
  SPEED_BONUS_FACTOR_FROM_DISTANCE: 0.25,
  ASTEROID_SPEED_RANDOM_ADD_MAX: 0.35,
  ASTEROID_XY_SWAY_FACTOR: 0.2,
  ASTEROID_SPAWN_Z: -150,
  ASTEROID_DESPAWN_Z: 20,
  ASTEROID_SPAWN_INTERVAL: 150,
};

export const WORMHOLE_CONSTANTS: WormholeConstants = {
  WORMHOLE_SPAWN_PROBABILITY: 0.04,
  WORMHOLE_RADIUS: 2.0,
  WORMHOLE_TUBE_RADIUS: 0.4,
  WORMHOLE_BASE_SPEED: 0.12,
  WORMHOLE_SPAWN_FIXED_Z: -100,
  WORMHOLE_ACTIVE_DURATION: 15000,
  WORMHOLE_XY_SPAWN_RANGE_FACTOR: 0.7,
  WORMHOLE_ROTATION_SPEED_MIN: 0.01,
  WORMHOLE_ROTATION_SPEED_RANGE: 0.02,
};

export const EXPLOSION_CONSTANTS: ExplosionConstants = {
  EXPLOSION_PARTICLE_COUNT: 70,
  EXPLOSION_PARTICLE_BASE_SPEED: 1.0,
  EXPLOSION_PARTICLE_LIFETIME_SECONDS: 3.5,
  EXPLOSION_PARTICLE_VELOCITY_DAMPING: 0.97,
  EXPLOSION_CENTER_DISTANCE_OFFSET: 2.5,
  EXPLOSION_PARTICLE_SPEED_BASE_FACTOR: 0.7,
  EXPLOSION_PARTICLE_SPEED_RANDOM_FACTOR: 0.6,
};

export const COSMIC_VELOCITY_CONSTANTS: CosmicVelocityConstants = {
  FIRST_COSMIC_VELOCITY_KMH: 28400,
  SECOND_COSMIC_VELOCITY_KMH: 40300,
  THIRD_COSMIC_VELOCITY_KMH: 60100,
};
